import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by drizzle-kit; not hand-written, not ours to lint/format.
    "lib/db/migrations/**",
    // Playwright's own output from local `pnpm test:e2e` runs — gitignored,
    // but not excluded from lint by eslint-config-next's defaults above.
    "playwright-report/**",
    "test-results/**",
    // Vitest coverage output — gitignored, but not excluded by the defaults.
    "coverage/**",
    // Stray agent worktrees (each a full checkout with its own
    // node_modules) can linger under here between sessions; never ours to
    // lint (see the matching vitest.config.ts exclude).
    ".claude/**",
  ]),
  // Must stay last: disables stylistic rules that would conflict with Prettier.
  prettierConfig,
]);

export default eslintConfig;
